file:
    - 'tests/functional/api/movies/index.js'
    - 'tests/functional/api/users/index.js'
    - 'tests/functional/api/upcoming/index.js'
    - 'tests/functional/api/popular/index.js'
    - 'tests/functional/api/toprated/index.js'
    - 'tests/functional/api/latest/index.js'
    - 'tests/functional/api/nowplaying/index.js'
    - 'tests/functional/api/actors/index.js'
require: '@babel/register'
exit: true
timeout: 7000
